---
- name: Ansible Sandbox Playbook (Linux)
  hosts: linux
  gather_facts: true
  become: false
  vars_prompt:
    - name: ansible_ssh_user
      prompt: "Enter SSH user"
      private: false
    - name: ansible_ssh_pass
      prompt: "Enter SSH password"
      private: true

  tasks:
    - name: Ping Server
      ansible.builtin.ping:
    - name: Output the system's hostname
      ansible.builtin.debug:
        msg: "The system's hostname is {{ ansible_hostname }}"
